class data {
  static List img = [
    "image1.jpeg",
    "image2.jpeg",
    "image3.jpeg",
    "image4.jpeg",
    "image5.jpeg",
    "image6.jpeg",
    "image7.jpeg",
    "image8.jpeg",
    "image9.jpeg",
    "image10.jpeg",
    "image11.jpeg",
    "image12.jpeg",
    "image13.jpeg",
    "image14.jpeg",
    "image15.jpeg",
    "image16.jpeg",
    "image17.jpeg",
    "image18.jpeg",
    "image19.jpeg",
    "image20.jpeg",
    "image21.jpeg",
    "image22.jpeg",
    "image23.jpeg",
    "image24.jpeg",
    "image25.jpeg",
    "image26.jpeg",
    "image27.jpeg",
    "image28.jpeg",
    "image29.jpeg",
  ];

  static List name = [
    "Where Do I Live",
    "Funny Faces Chain",
    "Musical Statues",
    "Hopocth",
    "Spotting Game",
    "Fierce Mr.Crocodile",
    "Running Statue",
    "Race To Base",
    "Big Fat Spiders",
    "Beach Trrget Game",
    "Hide And Seek",
    "Piggy In The Middle",
    "One Behind",
    "Word Finder",
    "What's My Hobby",
    "Squish Squash",
    "Bouncing Ball",
    "Talking Scraps",
    "Chasing Shadows",
    "Scuttling Crab Race",
    "Kice The Can",
    "Animals In The Zoo",
    "No Yes, No No",
    "Mixed Up Faces",
    "Ice Monster",
    "Hot And Cold",
    "Touch Tag",
    "Word Catch",
    "I Spy",
  ];
}
